name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # trigger on push to main branch
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}
      FRONTEND_IMAGE: ${{ secrets.FRONTEND_IMAGE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # ---------------- Backend ----------------
      - name: Build Backend Docker Image
        run: |
          docker build -t $BACKEND_IMAGE:latest ./backend

      - name: Push Backend Image
        run: |
          docker push $BACKEND_IMAGE:latest

      # ---------------- Frontend ----------------
      - name: Build Frontend Docker Image
        run: |
          docker build -t $FRONTEND_IMAGE:latest ./frontend

      - name: Push Frontend Image
        run: |
          docker push $FRONTEND_IMAGE:latest
